"""initial schema

Revision ID: 1272a77b9407
Revises: 
Create Date: 2026-04-23 15:58:24.378252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1272a77b9407'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource_types_active_code', 'resource_types', ['active', 'code'], unique=False)
    op.create_index(op.f('ix_resource_types_active'), 'resource_types', ['active'], unique=False)
    op.create_index(op.f('ix_resource_types_code'), 'resource_types', ['code'], unique=True)
    op.create_index(op.f('ix_resource_types_id'), 'resource_types', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roles_builtin', 'roles', ['builtin'], unique=False)
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token_jti', sa.String(length=64), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_login', 'users', ['login'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendors_active_name', 'vendors', ['active', 'name'], unique=False)
    op.create_index(op.f('ix_vendors_active'), 'vendors', ['active'], unique=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.create_table('work_package_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_name', name='uq_work_package_types_internal_name')
    )
    op.create_index('idx_work_package_types_position', 'work_package_types', ['position'], unique=False)
    op.create_index(op.f('ix_work_package_types_id'), 'work_package_types', ['id'], unique=False)
    op.create_index(op.f('ix_work_package_types_internal_name'), 'work_package_types', ['internal_name'], unique=True)
    op.create_index(op.f('ix_work_package_types_name'), 'work_package_types', ['name'], unique=False)
    op.create_index(op.f('ix_work_package_types_position'), 'work_package_types', ['position'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('status_explanation', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('version_of', sa.String(length=36), nullable=True),
    sa.Column('baseline_id', sa.String(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('category_other', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('is_version', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_of'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_active', 'projects', ['active'], unique=False)
    op.create_index('idx_projects_baseline_id', 'projects', ['baseline_id'], unique=False)
    op.create_index('idx_projects_category', 'projects', ['category'], unique=False)
    op.create_index('idx_projects_deleted_at', 'projects', ['deleted_at'], unique=False)
    op.create_index('idx_projects_end_date', 'projects', ['end_date'], unique=False)
    op.create_index('idx_projects_is_version', 'projects', ['is_version'], unique=False)
    op.create_index('idx_projects_name', 'projects', ['name'], unique=False)
    op.create_index('idx_projects_owner', 'projects', ['owner'], unique=False)
    op.create_index('idx_projects_parent_id', 'projects', ['parent_id'], unique=False)
    op.create_index('idx_projects_project_code', 'projects', ['project_code'], unique=False)
    op.create_index('idx_projects_public', 'projects', ['public'], unique=False)
    op.create_index('idx_projects_start_date', 'projects', ['start_date'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_version_of', 'projects', ['version_of'], unique=False)
    op.create_index(op.f('ix_projects_baseline_id'), 'projects', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_end_date'), 'projects', ['end_date'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_version'), 'projects', ['is_version'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_owner'), 'projects', ['owner'], unique=False)
    op.create_index(op.f('ix_projects_parent_id'), 'projects', ['parent_id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_projects_start_date'), 'projects', ['start_date'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_version_of'), 'projects', ['version_of'], unique=False)
    op.create_index('ux_projects_active_version_per_baseline', 'projects', ['version_of'], unique=True, sqlite_where=sa.text("is_version = 1 AND status != 'suspended' AND deleted_at IS NULL"), postgresql_where=sa.text("is_version = true AND status != 'suspended' AND deleted_at IS NULL"))
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('idx_revoked_tokens_expires', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index('idx_revoked_tokens_user', 'revoked_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meetings_created_by_id', 'meetings', ['created_by_id'], unique=False)
    op.create_index('idx_meetings_project_id', 'meetings', ['project_id'], unique=False)
    op.create_index('idx_meetings_scheduled_at', 'meetings', ['scheduled_at'], unique=False)
    op.create_index('idx_meetings_title', 'meetings', ['title'], unique=False)
    op.create_index(op.f('ix_meetings_created_by_id'), 'meetings', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_project_id'), 'meetings', ['project_id'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_meetings_title'), 'meetings', ['title'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('depends', sa.JSON(), nullable=True),
    sa.Column('cloned_from_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_milestones_project_live', 'milestones', ['project_id', 'deleted_at'], unique=False)
    op.create_index('idx_milestones_project_position', 'milestones', ['project_id', 'position'], unique=False)
    op.create_index(op.f('ix_milestones_cloned_from_id'), 'milestones', ['cloned_from_id'], unique=False)
    op.create_index(op.f('ix_milestones_deleted_at'), 'milestones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_name'), 'milestones', ['name'], unique=False)
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_milestones_status'), 'milestones', ['status'], unique=False)
    op.create_table('project_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_audit_logs_created_at', 'project_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_project_audit_logs_project_id', 'project_audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_audit_logs_action'), 'project_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_project_audit_logs_actor_id'), 'project_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_project_audit_logs_created_at'), 'project_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_audit_logs_id'), 'project_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_project_audit_logs_project_id'), 'project_audit_logs', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index('idx_project_members_created_at', 'project_members', ['created_at'], unique=False)
    op.create_index('idx_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('project_vendors',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'vendor_id')
    )
    op.create_index('idx_project_vendors_project', 'project_vendors', ['project_id'], unique=False)
    op.create_index('idx_project_vendors_vendor', 'project_vendors', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_project_vendors_project_id'), 'project_vendors', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_vendors_vendor_id'), 'project_vendors', ['vendor_id'], unique=False)
    op.create_table('work_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=100), nullable=False),
    sa.Column('done_ratio', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['work_packages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['work_package_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_packages_assignee_id', 'work_packages', ['assignee_id'], unique=False)
    op.create_index('idx_work_packages_parent_id', 'work_packages', ['parent_id'], unique=False)
    op.create_index('idx_work_packages_priority', 'work_packages', ['priority'], unique=False)
    op.create_index('idx_work_packages_project_id', 'work_packages', ['project_id'], unique=False)
    op.create_index('idx_work_packages_status', 'work_packages', ['status'], unique=False)
    op.create_index('idx_work_packages_subject', 'work_packages', ['subject'], unique=False)
    op.create_index('idx_work_packages_type_id', 'work_packages', ['type_id'], unique=False)
    op.create_index(op.f('ix_work_packages_assignee_id'), 'work_packages', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_work_packages_id'), 'work_packages', ['id'], unique=False)
    op.create_index(op.f('ix_work_packages_parent_id'), 'work_packages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_work_packages_priority'), 'work_packages', ['priority'], unique=False)
    op.create_index(op.f('ix_work_packages_project_id'), 'work_packages', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_packages_status'), 'work_packages', ['status'], unique=False)
    op.create_index(op.f('ix_work_packages_subject'), 'work_packages', ['subject'], unique=False)
    op.create_index(op.f('ix_work_packages_type_id'), 'work_packages', ['type_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('resource_mode', sa.String(length=10), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('cloned_from_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resource_mode IS NULL OR resource_mode IN ('count', 'details')", name='ck_activities_resource_mode'),
    sa.CheckConstraint("type IN ('standard', 'resource', 'transactional')", name='ck_activities_type'),
    sa.CheckConstraint('resource_count IS NULL OR resource_count >= 1', name='ck_activities_resource_count_positive'),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_milestone_live', 'activities', ['milestone_id', 'deleted_at'], unique=False)
    op.create_index('idx_activities_milestone_position', 'activities', ['milestone_id', 'position'], unique=False)
    op.create_index('idx_activities_project_live', 'activities', ['project_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_activities_cloned_from_id'), 'activities', ['cloned_from_id'], unique=False)
    op.create_index(op.f('ix_activities_deleted_at'), 'activities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_milestone_id'), 'activities', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=False)
    op.create_index(op.f('ix_activities_project_id'), 'activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_table('meeting_agenda_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('work_package_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agenda_items_meeting_id', 'meeting_agenda_items', ['meeting_id'], unique=False)
    op.create_index('idx_agenda_items_position', 'meeting_agenda_items', ['position'], unique=False)
    op.create_index('idx_agenda_items_project_id', 'meeting_agenda_items', ['project_id'], unique=False)
    op.create_index('idx_agenda_items_work_package_id', 'meeting_agenda_items', ['work_package_id'], unique=False)
    op.create_index(op.f('ix_meeting_agenda_items_id'), 'meeting_agenda_items', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_agenda_items_meeting_id'), 'meeting_agenda_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_agenda_items_position'), 'meeting_agenda_items', ['position'], unique=False)
    op.create_index(op.f('ix_meeting_agenda_items_project_id'), 'meeting_agenda_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_meeting_agenda_items_work_package_id'), 'meeting_agenda_items', ['work_package_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_user')
    )
    op.create_index('idx_meeting_participants_meeting_id', 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index('idx_meeting_participants_user_id', 'meeting_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_id'), 'meeting_participants', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_user_id'), 'meeting_participants', ['user_id'], unique=False)
    op.create_table('milestone_vendors',
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('milestone_id', 'vendor_id')
    )
    op.create_index('idx_milestone_vendors_milestone', 'milestone_vendors', ['milestone_id'], unique=False)
    op.create_index('idx_milestone_vendors_vendor', 'milestone_vendors', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_milestone_vendors_milestone_id'), 'milestone_vendors', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_milestone_vendors_vendor_id'), 'milestone_vendors', ['vendor_id'], unique=False)
    op.create_table('activity_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_activity_id', sa.String(length=36), nullable=False),
    sa.Column('target_activity_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['target_activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_deps_project_live', 'activity_dependencies', ['project_id', 'deleted_at'], unique=False)
    op.create_index('idx_activity_deps_source_live', 'activity_dependencies', ['source_activity_id', 'deleted_at'], unique=False)
    op.create_index('idx_activity_deps_target_live', 'activity_dependencies', ['target_activity_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_deleted_at'), 'activity_dependencies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_id'), 'activity_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_project_id'), 'activity_dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_source_activity_id'), 'activity_dependencies', ['source_activity_id'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_target_activity_id'), 'activity_dependencies', ['target_activity_id'], unique=False)
    op.create_index('uq_activity_deps_pair_live', 'activity_dependencies', ['source_activity_id', 'target_activity_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('activity_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('onboard_date', sa.DateTime(), nullable=True),
    sa.Column('actual_onboard_date', sa.DateTime(), nullable=True),
    sa.Column('offboard_date', sa.DateTime(), nullable=True),
    sa.Column('actual_offboard_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('job_role', sa.String(length=255), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('type_of_resource_id', sa.String(length=36), nullable=True),
    sa.Column('division', sa.String(length=32), nullable=True),
    sa.Column('division_other', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['type_of_resource_id'], ['resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_resources_project_live', 'activity_resources', ['project_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_resources_activity_id'), 'activity_resources', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_resources_deleted_at'), 'activity_resources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_resources_id'), 'activity_resources', ['id'], unique=False)
    op.create_index(op.f('ix_activity_resources_project_id'), 'activity_resources', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_resources_type_of_resource_id'), 'activity_resources', ['type_of_resource_id'], unique=False)
    op.create_index('uq_activity_resources_activity_live', 'activity_resources', ['activity_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('resource_mode', sa.String(length=10), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resource_mode IS NULL OR resource_mode IN ('count', 'details')", name='ck_tasks_resource_mode'),
    sa.CheckConstraint("type IN ('standard', 'resource', 'transactional')", name='ck_tasks_type'),
    sa.CheckConstraint('resource_count IS NULL OR resource_count >= 1', name='ck_tasks_resource_count_positive'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_activity_live', 'tasks', ['activity_id', 'deleted_at'], unique=False)
    op.create_index('idx_tasks_activity_position', 'tasks', ['activity_id', 'position'], unique=False)
    op.create_index('idx_tasks_project_live', 'tasks', ['project_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_activity_id'), 'tasks', ['activity_id'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('resource_mode', sa.String(length=10), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resource_mode IS NULL OR resource_mode IN ('count', 'details')", name='ck_subtasks_resource_mode'),
    sa.CheckConstraint("type IN ('standard', 'resource', 'transactional')", name='ck_subtasks_type'),
    sa.CheckConstraint('resource_count IS NULL OR resource_count >= 1', name='ck_subtasks_resource_count_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subtasks_project_live', 'subtasks', ['project_id', 'deleted_at'], unique=False)
    op.create_index('idx_subtasks_task_live', 'subtasks', ['task_id', 'deleted_at'], unique=False)
    op.create_index('idx_subtasks_task_position', 'subtasks', ['task_id', 'position'], unique=False)
    op.create_index(op.f('ix_subtasks_deleted_at'), 'subtasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.create_index(op.f('ix_subtasks_name'), 'subtasks', ['name'], unique=False)
    op.create_index(op.f('ix_subtasks_project_id'), 'subtasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_task_id', sa.String(length=36), nullable=False),
    sa.Column('target_task_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['target_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_deps_project_live', 'task_dependencies', ['project_id', 'deleted_at'], unique=False)
    op.create_index('idx_task_deps_source_live', 'task_dependencies', ['source_task_id', 'deleted_at'], unique=False)
    op.create_index('idx_task_deps_target_live', 'task_dependencies', ['target_task_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_task_dependencies_deleted_at'), 'task_dependencies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_dependencies_id'), 'task_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_project_id'), 'task_dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_source_task_id'), 'task_dependencies', ['source_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_target_task_id'), 'task_dependencies', ['target_task_id'], unique=False)
    op.create_index('uq_task_deps_pair_live', 'task_dependencies', ['source_task_id', 'target_task_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('task_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('onboard_date', sa.DateTime(), nullable=True),
    sa.Column('actual_onboard_date', sa.DateTime(), nullable=True),
    sa.Column('offboard_date', sa.DateTime(), nullable=True),
    sa.Column('actual_offboard_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('job_role', sa.String(length=255), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_resources_project_live', 'task_resources', ['project_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_task_resources_deleted_at'), 'task_resources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_resources_id'), 'task_resources', ['id'], unique=False)
    op.create_index(op.f('ix_task_resources_project_id'), 'task_resources', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_resources_task_id'), 'task_resources', ['task_id'], unique=False)
    op.create_index('uq_task_resources_task_live', 'task_resources', ['task_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('subtask_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_subtask_id', sa.String(length=36), nullable=False),
    sa.Column('target_subtask_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_subtask_id'], ['subtasks.id'], ),
    sa.ForeignKeyConstraint(['target_subtask_id'], ['subtasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subtask_deps_project_live', 'subtask_dependencies', ['project_id', 'deleted_at'], unique=False)
    op.create_index('idx_subtask_deps_source_live', 'subtask_dependencies', ['source_subtask_id', 'deleted_at'], unique=False)
    op.create_index('idx_subtask_deps_target_live', 'subtask_dependencies', ['target_subtask_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_subtask_dependencies_deleted_at'), 'subtask_dependencies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subtask_dependencies_id'), 'subtask_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_subtask_dependencies_project_id'), 'subtask_dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_subtask_dependencies_source_subtask_id'), 'subtask_dependencies', ['source_subtask_id'], unique=False)
    op.create_index(op.f('ix_subtask_dependencies_target_subtask_id'), 'subtask_dependencies', ['target_subtask_id'], unique=False)
    op.create_index('uq_subtask_deps_pair_live', 'subtask_dependencies', ['source_subtask_id', 'target_subtask_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('subtask_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subtask_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('onboard_date', sa.DateTime(), nullable=True),
    sa.Column('actual_onboard_date', sa.DateTime(), nullable=True),
    sa.Column('offboard_date', sa.DateTime(), nullable=True),
    sa.Column('actual_offboard_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('job_role', sa.String(length=255), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subtask_resources_project_live', 'subtask_resources', ['project_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_subtask_resources_deleted_at'), 'subtask_resources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subtask_resources_id'), 'subtask_resources', ['id'], unique=False)
    op.create_index(op.f('ix_subtask_resources_project_id'), 'subtask_resources', ['project_id'], unique=False)
    op.create_index(op.f('ix_subtask_resources_subtask_id'), 'subtask_resources', ['subtask_id'], unique=False)
    op.create_index('uq_subtask_resources_subtask_live', 'subtask_resources', ['subtask_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_subtask_resources_subtask_live', table_name='subtask_resources', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_subtask_resources_subtask_id'), table_name='subtask_resources')
    op.drop_index(op.f('ix_subtask_resources_project_id'), table_name='subtask_resources')
    op.drop_index(op.f('ix_subtask_resources_id'), table_name='subtask_resources')
    op.drop_index(op.f('ix_subtask_resources_deleted_at'), table_name='subtask_resources')
    op.drop_index('idx_subtask_resources_project_live', table_name='subtask_resources')
    op.drop_table('subtask_resources')
    op.drop_index('uq_subtask_deps_pair_live', table_name='subtask_dependencies', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_subtask_dependencies_target_subtask_id'), table_name='subtask_dependencies')
    op.drop_index(op.f('ix_subtask_dependencies_source_subtask_id'), table_name='subtask_dependencies')
    op.drop_index(op.f('ix_subtask_dependencies_project_id'), table_name='subtask_dependencies')
    op.drop_index(op.f('ix_subtask_dependencies_id'), table_name='subtask_dependencies')
    op.drop_index(op.f('ix_subtask_dependencies_deleted_at'), table_name='subtask_dependencies')
    op.drop_index('idx_subtask_deps_target_live', table_name='subtask_dependencies')
    op.drop_index('idx_subtask_deps_source_live', table_name='subtask_dependencies')
    op.drop_index('idx_subtask_deps_project_live', table_name='subtask_dependencies')
    op.drop_table('subtask_dependencies')
    op.drop_index('uq_task_resources_task_live', table_name='task_resources', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_task_resources_task_id'), table_name='task_resources')
    op.drop_index(op.f('ix_task_resources_project_id'), table_name='task_resources')
    op.drop_index(op.f('ix_task_resources_id'), table_name='task_resources')
    op.drop_index(op.f('ix_task_resources_deleted_at'), table_name='task_resources')
    op.drop_index('idx_task_resources_project_live', table_name='task_resources')
    op.drop_table('task_resources')
    op.drop_index('uq_task_deps_pair_live', table_name='task_dependencies', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_task_dependencies_target_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_source_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_project_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_deleted_at'), table_name='task_dependencies')
    op.drop_index('idx_task_deps_target_live', table_name='task_dependencies')
    op.drop_index('idx_task_deps_source_live', table_name='task_dependencies')
    op.drop_index('idx_task_deps_project_live', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_subtasks_task_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_project_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_name'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_deleted_at'), table_name='subtasks')
    op.drop_index('idx_subtasks_task_position', table_name='subtasks')
    op.drop_index('idx_subtasks_task_live', table_name='subtasks')
    op.drop_index('idx_subtasks_project_live', table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_activity_id'), table_name='tasks')
    op.drop_index('idx_tasks_project_live', table_name='tasks')
    op.drop_index('idx_tasks_activity_position', table_name='tasks')
    op.drop_index('idx_tasks_activity_live', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('uq_activity_resources_activity_live', table_name='activity_resources', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_activity_resources_type_of_resource_id'), table_name='activity_resources')
    op.drop_index(op.f('ix_activity_resources_project_id'), table_name='activity_resources')
    op.drop_index(op.f('ix_activity_resources_id'), table_name='activity_resources')
    op.drop_index(op.f('ix_activity_resources_deleted_at'), table_name='activity_resources')
    op.drop_index(op.f('ix_activity_resources_activity_id'), table_name='activity_resources')
    op.drop_index('idx_activity_resources_project_live', table_name='activity_resources')
    op.drop_table('activity_resources')
    op.drop_index('uq_activity_deps_pair_live', table_name='activity_dependencies', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_activity_dependencies_target_activity_id'), table_name='activity_dependencies')
    op.drop_index(op.f('ix_activity_dependencies_source_activity_id'), table_name='activity_dependencies')
    op.drop_index(op.f('ix_activity_dependencies_project_id'), table_name='activity_dependencies')
    op.drop_index(op.f('ix_activity_dependencies_id'), table_name='activity_dependencies')
    op.drop_index(op.f('ix_activity_dependencies_deleted_at'), table_name='activity_dependencies')
    op.drop_index('idx_activity_deps_target_live', table_name='activity_dependencies')
    op.drop_index('idx_activity_deps_source_live', table_name='activity_dependencies')
    op.drop_index('idx_activity_deps_project_live', table_name='activity_dependencies')
    op.drop_table('activity_dependencies')
    op.drop_index(op.f('ix_milestone_vendors_vendor_id'), table_name='milestone_vendors')
    op.drop_index(op.f('ix_milestone_vendors_milestone_id'), table_name='milestone_vendors')
    op.drop_index('idx_milestone_vendors_vendor', table_name='milestone_vendors')
    op.drop_index('idx_milestone_vendors_milestone', table_name='milestone_vendors')
    op.drop_table('milestone_vendors')
    op.drop_index(op.f('ix_meeting_participants_user_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_id'), table_name='meeting_participants')
    op.drop_index('idx_meeting_participants_user_id', table_name='meeting_participants')
    op.drop_index('idx_meeting_participants_meeting_id', table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_agenda_items_work_package_id'), table_name='meeting_agenda_items')
    op.drop_index(op.f('ix_meeting_agenda_items_project_id'), table_name='meeting_agenda_items')
    op.drop_index(op.f('ix_meeting_agenda_items_position'), table_name='meeting_agenda_items')
    op.drop_index(op.f('ix_meeting_agenda_items_meeting_id'), table_name='meeting_agenda_items')
    op.drop_index(op.f('ix_meeting_agenda_items_id'), table_name='meeting_agenda_items')
    op.drop_index('idx_agenda_items_work_package_id', table_name='meeting_agenda_items')
    op.drop_index('idx_agenda_items_project_id', table_name='meeting_agenda_items')
    op.drop_index('idx_agenda_items_position', table_name='meeting_agenda_items')
    op.drop_index('idx_agenda_items_meeting_id', table_name='meeting_agenda_items')
    op.drop_table('meeting_agenda_items')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_project_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_index(op.f('ix_activities_milestone_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_deleted_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_cloned_from_id'), table_name='activities')
    op.drop_index('idx_activities_project_live', table_name='activities')
    op.drop_index('idx_activities_milestone_position', table_name='activities')
    op.drop_index('idx_activities_milestone_live', table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_work_packages_type_id'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_subject'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_status'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_project_id'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_priority'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_parent_id'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_id'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_assignee_id'), table_name='work_packages')
    op.drop_index('idx_work_packages_type_id', table_name='work_packages')
    op.drop_index('idx_work_packages_subject', table_name='work_packages')
    op.drop_index('idx_work_packages_status', table_name='work_packages')
    op.drop_index('idx_work_packages_project_id', table_name='work_packages')
    op.drop_index('idx_work_packages_priority', table_name='work_packages')
    op.drop_index('idx_work_packages_parent_id', table_name='work_packages')
    op.drop_index('idx_work_packages_assignee_id', table_name='work_packages')
    op.drop_table('work_packages')
    op.drop_index(op.f('ix_project_vendors_vendor_id'), table_name='project_vendors')
    op.drop_index(op.f('ix_project_vendors_project_id'), table_name='project_vendors')
    op.drop_index('idx_project_vendors_vendor', table_name='project_vendors')
    op.drop_index('idx_project_vendors_project', table_name='project_vendors')
    op.drop_table('project_vendors')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_index('idx_project_members_user_id', table_name='project_members')
    op.drop_index('idx_project_members_project_id', table_name='project_members')
    op.drop_index('idx_project_members_created_at', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_audit_logs_project_id'), table_name='project_audit_logs')
    op.drop_index(op.f('ix_project_audit_logs_id'), table_name='project_audit_logs')
    op.drop_index(op.f('ix_project_audit_logs_created_at'), table_name='project_audit_logs')
    op.drop_index(op.f('ix_project_audit_logs_actor_id'), table_name='project_audit_logs')
    op.drop_index(op.f('ix_project_audit_logs_action'), table_name='project_audit_logs')
    op.drop_index('idx_project_audit_logs_project_id', table_name='project_audit_logs')
    op.drop_index('idx_project_audit_logs_created_at', table_name='project_audit_logs')
    op.drop_table('project_audit_logs')
    op.drop_index(op.f('ix_milestones_status'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_name'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_deleted_at'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_cloned_from_id'), table_name='milestones')
    op.drop_index('idx_milestones_project_position', table_name='milestones')
    op.drop_index('idx_milestones_project_live', table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_meetings_title'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_project_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_by_id'), table_name='meetings')
    op.drop_index('idx_meetings_title', table_name='meetings')
    op.drop_index('idx_meetings_scheduled_at', table_name='meetings')
    op.drop_index('idx_meetings_project_id', table_name='meetings')
    op.drop_index('idx_meetings_created_by_id', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.drop_index('idx_revoked_tokens_user', table_name='revoked_tokens')
    op.drop_index('idx_revoked_tokens_expires', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index('ux_projects_active_version_per_baseline', table_name='projects', sqlite_where=sa.text("is_version = 1 AND status != 'suspended' AND deleted_at IS NULL"), postgresql_where=sa.text("is_version = true AND status != 'suspended' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_projects_version_of'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_start_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_parent_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_version'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_end_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_index(op.f('ix_projects_baseline_id'), table_name='projects')
    op.drop_index('idx_projects_version_of', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_start_date', table_name='projects')
    op.drop_index('idx_projects_public', table_name='projects')
    op.drop_index('idx_projects_project_code', table_name='projects')
    op.drop_index('idx_projects_parent_id', table_name='projects')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.drop_index('idx_projects_name', table_name='projects')
    op.drop_index('idx_projects_is_version', table_name='projects')
    op.drop_index('idx_projects_end_date', table_name='projects')
    op.drop_index('idx_projects_deleted_at', table_name='projects')
    op.drop_index('idx_projects_category', table_name='projects')
    op.drop_index('idx_projects_baseline_id', table_name='projects')
    op.drop_index('idx_projects_active', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_work_package_types_position'), table_name='work_package_types')
    op.drop_index(op.f('ix_work_package_types_name'), table_name='work_package_types')
    op.drop_index(op.f('ix_work_package_types_internal_name'), table_name='work_package_types')
    op.drop_index(op.f('ix_work_package_types_id'), table_name='work_package_types')
    op.drop_index('idx_work_package_types_position', table_name='work_package_types')
    op.drop_table('work_package_types')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_active'), table_name='vendors')
    op.drop_index('idx_vendors_active_name', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_login', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index('idx_roles_name', table_name='roles')
    op.drop_index('idx_roles_builtin', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resource_types_id'), table_name='resource_types')
    op.drop_index(op.f('ix_resource_types_code'), table_name='resource_types')
    op.drop_index(op.f('ix_resource_types_active'), table_name='resource_types')
    op.drop_index('idx_resource_types_active_code', table_name='resource_types')
    op.drop_table('resource_types')
    # ### end Alembic commands ###
