"""add comments and attachments tables

Revision ID: 4825a33f9ed3
Revises: eb3b19c7487c
Create Date: 2026-04-27 18:43:32.195584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4825a33f9ed3'
down_revision: Union[str, Sequence[str], None] = 'eb3b19c7487c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_kind', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('idx_comments_target', 'comments', ['target_kind', 'target_id'], unique=False)
    op.create_index('idx_comments_target_active', 'comments', ['target_kind', 'target_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_author_user_id'), 'comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=True),
    sa.Column('target_kind', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('idx_attachments_target', 'attachments', ['target_kind', 'target_id'], unique=False)
    op.create_index('idx_attachments_target_active', 'attachments', ['target_kind', 'target_id', 'deleted_at'], unique=False)
    op.create_index('idx_attachments_uploaded_at', 'attachments', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_attachments_comment_id'), 'attachments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_attachments_deleted_at'), 'attachments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_attachments_uploaded_by_user_id'), 'attachments', ['uploaded_by_user_id'], unique=False)
    # NOTE: autogenerate also wanted to drop ``alembic_version_user_svc``
    # but that belongs to the SEPARATE pmis-user-service Alembic chain
    # sharing this database. Intentionally NOT dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_attachments_uploaded_by_user_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_deleted_at'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_comment_id'), table_name='attachments')
    op.drop_index('idx_attachments_uploaded_at', table_name='attachments')
    op.drop_index('idx_attachments_target_active', table_name='attachments')
    op.drop_index('idx_attachments_target', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_user_id'), table_name='comments')
    op.drop_index('idx_comments_target_active', table_name='comments')
    op.drop_index('idx_comments_target', table_name='comments')
    op.drop_index('idx_comments_created_at', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
