"""add catalog tables and category_other_reason

Revision ID: f9b8dd81f7dd
Revises: 1272a77b9407
Create Date: 2026-04-24 12:44:21.365669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b8dd81f7dd'
down_revision: Union[str, Sequence[str], None] = '1272a77b9407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_status_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('requires_admin', sa.Boolean(), nullable=False),
    sa.Column('version_only', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_status', 'to_status', name='uq_project_status_transitions_edge')
    )
    op.create_index('idx_pst_to_status_active', 'project_status_transitions', ['to_status', 'active'], unique=False)
    op.create_index(op.f('ix_project_status_transitions_active'), 'project_status_transitions', ['active'], unique=False)
    op.create_index(op.f('ix_project_status_transitions_from_status'), 'project_status_transitions', ['from_status'], unique=False)
    op.create_index(op.f('ix_project_status_transitions_to_status'), 'project_status_transitions', ['to_status'], unique=False)
    op.create_table('project_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_project_owners_user_id')
    )
    op.create_index('idx_project_owners_active_user', 'project_owners', ['active', 'user_id'], unique=False)
    op.create_index(op.f('ix_project_owners_active'), 'project_owners', ['active'], unique=False)
    op.add_column('projects', sa.Column('category_other_reason', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'category_other_reason')
    op.drop_index(op.f('ix_project_owners_active'), table_name='project_owners')
    op.drop_index('idx_project_owners_active_user', table_name='project_owners')
    op.drop_table('project_owners')
    op.drop_index(op.f('ix_project_status_transitions_to_status'), table_name='project_status_transitions')
    op.drop_index(op.f('ix_project_status_transitions_from_status'), table_name='project_status_transitions')
    op.drop_index(op.f('ix_project_status_transitions_active'), table_name='project_status_transitions')
    op.drop_index('idx_pst_to_status_active', table_name='project_status_transitions')
    op.drop_table('project_status_transitions')
    # ### end Alembic commands ###
