-- Auto-generated by scripts/generate_ddl.py — DO NOT edit.
-- Dialect: sqlite
-- Source: SQLAlchemy Base.metadata

-- ===== activities =====
CREATE TABLE activities (
	id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	milestone_id VARCHAR(36) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	type VARCHAR(20) NOT NULL, 
	start_date DATETIME NOT NULL, 
	end_date DATETIME NOT NULL, 
	actual_start_date DATETIME, 
	actual_end_date DATETIME, 
	position INTEGER NOT NULL, 
	resource_mode VARCHAR(10), 
	resource_count INTEGER, 
	status VARCHAR(32), 
	cloned_from_id VARCHAR(36), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	created_by VARCHAR(36), 
	updated_by VARCHAR(36), 
	deleted_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_activities_type CHECK (type IN ('standard', 'resource', 'transactional')), 
	CONSTRAINT ck_activities_resource_mode CHECK (resource_mode IS NULL OR resource_mode IN ('count', 'details')), 
	CONSTRAINT ck_activities_resource_count_positive CHECK (resource_count IS NULL OR resource_count >= 1), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(milestone_id) REFERENCES milestones (id), 
	FOREIGN KEY(cloned_from_id) REFERENCES activities (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(updated_by) REFERENCES users (id)
);
CREATE INDEX idx_activities_milestone_live ON activities (milestone_id, deleted_at);
CREATE INDEX idx_activities_milestone_position ON activities (milestone_id, position);
CREATE INDEX idx_activities_project_live ON activities (project_id, deleted_at);
CREATE INDEX ix_activities_cloned_from_id ON activities (cloned_from_id);
CREATE INDEX ix_activities_deleted_at ON activities (deleted_at);
CREATE INDEX ix_activities_id ON activities (id);
CREATE INDEX ix_activities_milestone_id ON activities (milestone_id);
CREATE INDEX ix_activities_name ON activities (name);
CREATE INDEX ix_activities_project_id ON activities (project_id);
CREATE INDEX ix_activities_status ON activities (status);
CREATE UNIQUE INDEX uq_activities_milestone_position_live ON activities (milestone_id, position) WHERE deleted_at IS NULL;

-- ===== activity_dependencies =====
CREATE TABLE activity_dependencies (
	id VARCHAR(36) NOT NULL, 
	source_activity_id VARCHAR(36) NOT NULL, 
	target_activity_id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	FOREIGN KEY(source_activity_id) REFERENCES activities (id), 
	FOREIGN KEY(target_activity_id) REFERENCES activities (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_activity_deps_project_live ON activity_dependencies (project_id, deleted_at);
CREATE INDEX idx_activity_deps_source_live ON activity_dependencies (source_activity_id, deleted_at);
CREATE INDEX idx_activity_deps_target_live ON activity_dependencies (target_activity_id, deleted_at);
CREATE INDEX ix_activity_dependencies_deleted_at ON activity_dependencies (deleted_at);
CREATE INDEX ix_activity_dependencies_id ON activity_dependencies (id);
CREATE INDEX ix_activity_dependencies_project_id ON activity_dependencies (project_id);
CREATE INDEX ix_activity_dependencies_source_activity_id ON activity_dependencies (source_activity_id);
CREATE INDEX ix_activity_dependencies_target_activity_id ON activity_dependencies (target_activity_id);
CREATE UNIQUE INDEX uq_activity_deps_pair_live ON activity_dependencies (source_activity_id, target_activity_id) WHERE deleted_at IS NULL;

-- ===== activity_resources =====
CREATE TABLE activity_resources (
	id VARCHAR(36) NOT NULL, 
	activity_id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	resource_name VARCHAR(255) NOT NULL, 
	onboard_date DATETIME, 
	actual_onboard_date DATETIME, 
	offboard_date DATETIME, 
	actual_offboard_date DATETIME, 
	position VARCHAR(255), 
	designation VARCHAR(255), 
	job_role VARCHAR(255), 
	qualification VARCHAR(255), 
	experience_years NUMERIC(4, 1), 
	type_of_resource_id VARCHAR(36), 
	division VARCHAR(32), 
	division_other VARCHAR(255), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(activity_id) REFERENCES activities (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(type_of_resource_id) REFERENCES resource_types (id)
);
CREATE INDEX idx_activity_resources_project_live ON activity_resources (project_id, deleted_at);
CREATE INDEX ix_activity_resources_activity_id ON activity_resources (activity_id);
CREATE INDEX ix_activity_resources_deleted_at ON activity_resources (deleted_at);
CREATE INDEX ix_activity_resources_id ON activity_resources (id);
CREATE INDEX ix_activity_resources_project_id ON activity_resources (project_id);
CREATE INDEX ix_activity_resources_type_of_resource_id ON activity_resources (type_of_resource_id);
CREATE UNIQUE INDEX uq_activity_resources_activity_live ON activity_resources (activity_id) WHERE deleted_at IS NULL;

-- ===== attachments =====
CREATE TABLE attachments (
	id VARCHAR(36) NOT NULL, 
	comment_id VARCHAR(36), 
	target_kind VARCHAR(20), 
	target_id VARCHAR(36), 
	original_filename VARCHAR(500) NOT NULL, 
	storage_key VARCHAR(500) NOT NULL, 
	mime_type VARCHAR(100) NOT NULL, 
	size_bytes BIGINT NOT NULL, 
	uploaded_by_user_id VARCHAR(36) NOT NULL, 
	uploaded_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	FOREIGN KEY(comment_id) REFERENCES comments (id), 
	UNIQUE (storage_key), 
	FOREIGN KEY(uploaded_by_user_id) REFERENCES users (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_attachments_target ON attachments (target_kind, target_id);
CREATE INDEX idx_attachments_target_active ON attachments (target_kind, target_id, deleted_at);
CREATE INDEX idx_attachments_uploaded_at ON attachments (uploaded_at);
CREATE INDEX ix_attachments_comment_id ON attachments (comment_id);
CREATE INDEX ix_attachments_deleted_at ON attachments (deleted_at);
CREATE INDEX ix_attachments_uploaded_by_user_id ON attachments (uploaded_by_user_id);

-- ===== comments =====
CREATE TABLE comments (
	id VARCHAR(36) NOT NULL, 
	target_kind VARCHAR(20) NOT NULL, 
	target_id VARCHAR(36) NOT NULL, 
	body TEXT NOT NULL, 
	author_user_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	FOREIGN KEY(author_user_id) REFERENCES users (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_comments_created_at ON comments (created_at);
CREATE INDEX idx_comments_target ON comments (target_kind, target_id);
CREATE INDEX idx_comments_target_active ON comments (target_kind, target_id, deleted_at);
CREATE INDEX ix_comments_author_user_id ON comments (author_user_id);
CREATE INDEX ix_comments_deleted_at ON comments (deleted_at);

-- ===== divisions =====
CREATE TABLE divisions (
	id INTEGER NOT NULL, 
	code VARCHAR(64) NOT NULL, 
	label VARCHAR(255) NOT NULL, 
	is_builtin BOOLEAN NOT NULL, 
	requires_other BOOLEAN NOT NULL, 
	active BOOLEAN NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX idx_divisions_code_active ON divisions (code, active);
CREATE INDEX ix_divisions_active ON divisions (active);
CREATE UNIQUE INDEX ix_divisions_code ON divisions (code);

-- ===== meeting_agenda_items =====
CREATE TABLE meeting_agenda_items (
	id INTEGER NOT NULL, 
	meeting_id INTEGER NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	description TEXT, 
	position INTEGER NOT NULL, 
	work_package_id INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(meeting_id) REFERENCES meetings (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(work_package_id) REFERENCES work_packages (id)
);
CREATE INDEX idx_agenda_items_meeting_id ON meeting_agenda_items (meeting_id);
CREATE INDEX idx_agenda_items_position ON meeting_agenda_items (position);
CREATE INDEX idx_agenda_items_project_id ON meeting_agenda_items (project_id);
CREATE INDEX idx_agenda_items_work_package_id ON meeting_agenda_items (work_package_id);
CREATE INDEX ix_meeting_agenda_items_id ON meeting_agenda_items (id);
CREATE INDEX ix_meeting_agenda_items_meeting_id ON meeting_agenda_items (meeting_id);
CREATE INDEX ix_meeting_agenda_items_position ON meeting_agenda_items (position);
CREATE INDEX ix_meeting_agenda_items_project_id ON meeting_agenda_items (project_id);
CREATE INDEX ix_meeting_agenda_items_work_package_id ON meeting_agenda_items (work_package_id);

-- ===== meeting_participants =====
CREATE TABLE meeting_participants (
	id INTEGER NOT NULL, 
	meeting_id INTEGER NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_meeting_user UNIQUE (meeting_id, user_id), 
	FOREIGN KEY(meeting_id) REFERENCES meetings (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);
CREATE INDEX idx_meeting_participants_meeting_id ON meeting_participants (meeting_id);
CREATE INDEX idx_meeting_participants_user_id ON meeting_participants (user_id);
CREATE INDEX ix_meeting_participants_id ON meeting_participants (id);
CREATE INDEX ix_meeting_participants_meeting_id ON meeting_participants (meeting_id);
CREATE INDEX ix_meeting_participants_user_id ON meeting_participants (user_id);

-- ===== meetings =====
CREATE TABLE meetings (
	id INTEGER NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	description TEXT, 
	scheduled_at DATETIME NOT NULL, 
	duration_minutes INTEGER, 
	location VARCHAR(255), 
	created_by_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(created_by_id) REFERENCES users (id)
);
CREATE INDEX idx_meetings_created_by_id ON meetings (created_by_id);
CREATE INDEX idx_meetings_project_id ON meetings (project_id);
CREATE INDEX idx_meetings_scheduled_at ON meetings (scheduled_at);
CREATE INDEX idx_meetings_title ON meetings (title);
CREATE INDEX ix_meetings_created_by_id ON meetings (created_by_id);
CREATE INDEX ix_meetings_id ON meetings (id);
CREATE INDEX ix_meetings_project_id ON meetings (project_id);
CREATE INDEX ix_meetings_scheduled_at ON meetings (scheduled_at);
CREATE INDEX ix_meetings_title ON meetings (title);

-- ===== milestone_dependencies =====
CREATE TABLE milestone_dependencies (
	id VARCHAR(36) NOT NULL, 
	source_milestone_id VARCHAR(36) NOT NULL, 
	target_milestone_id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	FOREIGN KEY(source_milestone_id) REFERENCES milestones (id), 
	FOREIGN KEY(target_milestone_id) REFERENCES milestones (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_milestone_deps_project_live ON milestone_dependencies (project_id, deleted_at);
CREATE INDEX idx_milestone_deps_source_live ON milestone_dependencies (source_milestone_id, deleted_at);
CREATE INDEX idx_milestone_deps_target_live ON milestone_dependencies (target_milestone_id, deleted_at);
CREATE INDEX ix_milestone_dependencies_deleted_at ON milestone_dependencies (deleted_at);
CREATE INDEX ix_milestone_dependencies_id ON milestone_dependencies (id);
CREATE INDEX ix_milestone_dependencies_project_id ON milestone_dependencies (project_id);
CREATE INDEX ix_milestone_dependencies_source_milestone_id ON milestone_dependencies (source_milestone_id);
CREATE INDEX ix_milestone_dependencies_target_milestone_id ON milestone_dependencies (target_milestone_id);
CREATE UNIQUE INDEX uq_milestone_deps_pair_live ON milestone_dependencies (source_milestone_id, target_milestone_id) WHERE deleted_at IS NULL;

-- ===== milestone_vendors =====
CREATE TABLE milestone_vendors (
	milestone_id VARCHAR(36) NOT NULL, 
	vendor_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (milestone_id, vendor_id), 
	FOREIGN KEY(milestone_id) REFERENCES milestones (id), 
	FOREIGN KEY(vendor_id) REFERENCES vendors (id)
);
CREATE INDEX idx_milestone_vendors_milestone ON milestone_vendors (milestone_id);
CREATE INDEX idx_milestone_vendors_vendor ON milestone_vendors (vendor_id);
CREATE INDEX ix_milestone_vendors_milestone_id ON milestone_vendors (milestone_id);
CREATE INDEX ix_milestone_vendors_vendor_id ON milestone_vendors (vendor_id);

-- ===== milestones =====
CREATE TABLE milestones (
	id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	start_date DATETIME NOT NULL, 
	end_date DATETIME NOT NULL, 
	position INTEGER NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	cloned_from_id VARCHAR(36), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	created_by VARCHAR(36), 
	updated_by VARCHAR(36), 
	deleted_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(cloned_from_id) REFERENCES milestones (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(updated_by) REFERENCES users (id)
);
CREATE INDEX idx_milestones_project_live ON milestones (project_id, deleted_at);
CREATE INDEX idx_milestones_project_position ON milestones (project_id, position);
CREATE INDEX ix_milestones_cloned_from_id ON milestones (cloned_from_id);
CREATE INDEX ix_milestones_deleted_at ON milestones (deleted_at);
CREATE INDEX ix_milestones_id ON milestones (id);
CREATE INDEX ix_milestones_name ON milestones (name);
CREATE INDEX ix_milestones_project_id ON milestones (project_id);
CREATE INDEX ix_milestones_status ON milestones (status);
CREATE UNIQUE INDEX uq_milestones_project_position_live ON milestones (project_id, position) WHERE deleted_at IS NULL;

-- ===== permissions =====
CREATE TABLE permissions (
	code VARCHAR(128) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description VARCHAR(1024), 
	is_builtin BOOLEAN NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (code)
);

-- ===== project_audit_logs =====
CREATE TABLE project_audit_logs (
	id INTEGER NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	actor_id VARCHAR(36), 
	action VARCHAR(64) NOT NULL, 
	"before" JSON, 
	"after" JSON, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(actor_id) REFERENCES users (id)
);
CREATE INDEX idx_project_audit_logs_created_at ON project_audit_logs (created_at);
CREATE INDEX idx_project_audit_logs_project_id ON project_audit_logs (project_id);
CREATE INDEX ix_project_audit_logs_action ON project_audit_logs (action);
CREATE INDEX ix_project_audit_logs_actor_id ON project_audit_logs (actor_id);
CREATE INDEX ix_project_audit_logs_created_at ON project_audit_logs (created_at);
CREATE INDEX ix_project_audit_logs_id ON project_audit_logs (id);
CREATE INDEX ix_project_audit_logs_project_id ON project_audit_logs (project_id);

-- ===== project_members =====
CREATE TABLE project_members (
	id INTEGER NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	roles JSON NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_project_user UNIQUE (project_id, user_id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);
CREATE INDEX idx_project_members_created_at ON project_members (created_at);
CREATE INDEX idx_project_members_project_id ON project_members (project_id);
CREATE INDEX idx_project_members_user_id ON project_members (user_id);
CREATE INDEX ix_project_members_id ON project_members (id);
CREATE INDEX ix_project_members_project_id ON project_members (project_id);
CREATE INDEX ix_project_members_user_id ON project_members (user_id);

-- ===== project_status_transitions =====
CREATE TABLE project_status_transitions (
	id INTEGER NOT NULL, 
	from_status VARCHAR(50), 
	to_status VARCHAR(50) NOT NULL, 
	requires_admin BOOLEAN NOT NULL, 
	version_only BOOLEAN NOT NULL, 
	active BOOLEAN NOT NULL, 
	description VARCHAR(500), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_project_status_transitions_edge UNIQUE (from_status, to_status)
);
CREATE INDEX idx_pst_to_status_active ON project_status_transitions (to_status, active);
CREATE INDEX ix_project_status_transitions_active ON project_status_transitions (active);
CREATE INDEX ix_project_status_transitions_from_status ON project_status_transitions (from_status);
CREATE INDEX ix_project_status_transitions_to_status ON project_status_transitions (to_status);

-- ===== project_vendors =====
CREATE TABLE project_vendors (
	project_id VARCHAR(36) NOT NULL, 
	vendor_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (project_id, vendor_id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(vendor_id) REFERENCES vendors (id)
);
CREATE INDEX idx_project_vendors_project ON project_vendors (project_id);
CREATE INDEX idx_project_vendors_vendor ON project_vendors (vendor_id);
CREATE INDEX ix_project_vendors_project_id ON project_vendors (project_id);
CREATE INDEX ix_project_vendors_vendor_id ON project_vendors (vendor_id);

-- ===== projects =====
CREATE TABLE projects (
	id VARCHAR(36) NOT NULL, 
	project_code VARCHAR(30) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	active BOOLEAN NOT NULL, 
	public BOOLEAN NOT NULL, 
	status_explanation TEXT, 
	parent_id VARCHAR(36), 
	version_of VARCHAR(36), 
	baseline_id VARCHAR(36), 
	version_no INTEGER, 
	status VARCHAR(50) NOT NULL, 
	owner VARCHAR(255), 
	owner_other VARCHAR(255), 
	category VARCHAR(50), 
	category_other VARCHAR(255), 
	category_other_reason VARCHAR(1000), 
	start_date DATETIME, 
	end_date DATETIME, 
	actual_start_date DATETIME, 
	actual_end_date DATETIME, 
	is_version BOOLEAN NOT NULL, 
	created_by VARCHAR(36), 
	updated_by VARCHAR(36), 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(parent_id) REFERENCES projects (id), 
	FOREIGN KEY(version_of) REFERENCES projects (id), 
	FOREIGN KEY(baseline_id) REFERENCES projects (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(updated_by) REFERENCES users (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_projects_active ON projects (active);
CREATE INDEX idx_projects_baseline_id ON projects (baseline_id);
CREATE INDEX idx_projects_category ON projects (category);
CREATE INDEX idx_projects_deleted_at ON projects (deleted_at);
CREATE INDEX idx_projects_end_date ON projects (end_date);
CREATE INDEX idx_projects_is_version ON projects (is_version);
CREATE INDEX idx_projects_name ON projects (name);
CREATE INDEX idx_projects_owner ON projects (owner);
CREATE INDEX idx_projects_parent_id ON projects (parent_id);
CREATE INDEX idx_projects_project_code ON projects (project_code);
CREATE INDEX idx_projects_public ON projects (public);
CREATE INDEX idx_projects_start_date ON projects (start_date);
CREATE INDEX idx_projects_status ON projects (status);
CREATE INDEX idx_projects_version_of ON projects (version_of);
CREATE INDEX ix_projects_baseline_id ON projects (baseline_id);
CREATE INDEX ix_projects_category ON projects (category);
CREATE INDEX ix_projects_deleted_at ON projects (deleted_at);
CREATE INDEX ix_projects_end_date ON projects (end_date);
CREATE INDEX ix_projects_id ON projects (id);
CREATE INDEX ix_projects_is_version ON projects (is_version);
CREATE INDEX ix_projects_name ON projects (name);
CREATE INDEX ix_projects_owner ON projects (owner);
CREATE INDEX ix_projects_parent_id ON projects (parent_id);
CREATE UNIQUE INDEX ix_projects_project_code ON projects (project_code);
CREATE INDEX ix_projects_start_date ON projects (start_date);
CREATE INDEX ix_projects_status ON projects (status);
CREATE INDEX ix_projects_version_of ON projects (version_of);
CREATE UNIQUE INDEX ux_projects_active_version_per_baseline ON projects (version_of) WHERE is_version = 1 AND status != 'suspended' AND deleted_at IS NULL;

-- ===== resource_types =====
CREATE TABLE resource_types (
	id VARCHAR(36) NOT NULL, 
	code VARCHAR(50) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	active BOOLEAN NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX idx_resource_types_active_code ON resource_types (active, code);
CREATE INDEX ix_resource_types_active ON resource_types (active);
CREATE UNIQUE INDEX ix_resource_types_code ON resource_types (code);
CREATE INDEX ix_resource_types_id ON resource_types (id);

-- ===== revoked_tokens =====
CREATE TABLE revoked_tokens (
	jti VARCHAR(64) NOT NULL, 
	user_id VARCHAR(36), 
	revoked_at DATETIME NOT NULL, 
	expires_at DATETIME NOT NULL, 
	PRIMARY KEY (jti), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);
CREATE INDEX idx_revoked_tokens_expires ON revoked_tokens (expires_at);
CREATE INDEX idx_revoked_tokens_user ON revoked_tokens (user_id);
CREATE INDEX ix_revoked_tokens_expires_at ON revoked_tokens (expires_at);
CREATE INDEX ix_revoked_tokens_jti ON revoked_tokens (jti);
CREATE INDEX ix_revoked_tokens_user_id ON revoked_tokens (user_id);

-- ===== role_permissions =====
CREATE TABLE role_permissions (
	role_id INTEGER NOT NULL, 
	permission_code VARCHAR(128) NOT NULL, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (role_id, permission_code), 
	FOREIGN KEY(role_id) REFERENCES roles (id), 
	FOREIGN KEY(permission_code) REFERENCES permissions (code)
);
CREATE INDEX idx_role_permissions_permission ON role_permissions (permission_code);
CREATE INDEX idx_role_permissions_role ON role_permissions (role_id);

-- ===== roles =====
CREATE TABLE roles (
	id INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description VARCHAR(1024), 
	builtin BOOLEAN NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX idx_roles_builtin ON roles (builtin);
CREATE INDEX idx_roles_name ON roles (name);
CREATE INDEX ix_roles_id ON roles (id);
CREATE UNIQUE INDEX ix_roles_name ON roles (name);

-- ===== subtask_dependencies =====
CREATE TABLE subtask_dependencies (
	id VARCHAR(36) NOT NULL, 
	source_subtask_id VARCHAR(36) NOT NULL, 
	target_subtask_id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	FOREIGN KEY(source_subtask_id) REFERENCES subtasks (id), 
	FOREIGN KEY(target_subtask_id) REFERENCES subtasks (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_subtask_deps_project_live ON subtask_dependencies (project_id, deleted_at);
CREATE INDEX idx_subtask_deps_source_live ON subtask_dependencies (source_subtask_id, deleted_at);
CREATE INDEX idx_subtask_deps_target_live ON subtask_dependencies (target_subtask_id, deleted_at);
CREATE INDEX ix_subtask_dependencies_deleted_at ON subtask_dependencies (deleted_at);
CREATE INDEX ix_subtask_dependencies_id ON subtask_dependencies (id);
CREATE INDEX ix_subtask_dependencies_project_id ON subtask_dependencies (project_id);
CREATE INDEX ix_subtask_dependencies_source_subtask_id ON subtask_dependencies (source_subtask_id);
CREATE INDEX ix_subtask_dependencies_target_subtask_id ON subtask_dependencies (target_subtask_id);
CREATE UNIQUE INDEX uq_subtask_deps_pair_live ON subtask_dependencies (source_subtask_id, target_subtask_id) WHERE deleted_at IS NULL;

-- ===== subtask_resources =====
CREATE TABLE subtask_resources (
	id VARCHAR(36) NOT NULL, 
	subtask_id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	resource_name VARCHAR(255) NOT NULL, 
	onboard_date DATETIME, 
	actual_onboard_date DATETIME, 
	offboard_date DATETIME, 
	actual_offboard_date DATETIME, 
	position VARCHAR(255), 
	designation VARCHAR(255), 
	job_role VARCHAR(255), 
	qualification VARCHAR(255), 
	experience_years NUMERIC(4, 1), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(subtask_id) REFERENCES subtasks (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id)
);
CREATE INDEX idx_subtask_resources_project_live ON subtask_resources (project_id, deleted_at);
CREATE INDEX ix_subtask_resources_deleted_at ON subtask_resources (deleted_at);
CREATE INDEX ix_subtask_resources_id ON subtask_resources (id);
CREATE INDEX ix_subtask_resources_project_id ON subtask_resources (project_id);
CREATE INDEX ix_subtask_resources_subtask_id ON subtask_resources (subtask_id);
CREATE UNIQUE INDEX uq_subtask_resources_subtask_live ON subtask_resources (subtask_id) WHERE deleted_at IS NULL;

-- ===== subtasks =====
CREATE TABLE subtasks (
	id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	task_id VARCHAR(36) NOT NULL, 
	parent_subtask_id VARCHAR(36), 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	type VARCHAR(20) NOT NULL, 
	start_date DATETIME NOT NULL, 
	end_date DATETIME NOT NULL, 
	actual_start_date DATETIME, 
	actual_end_date DATETIME, 
	position INTEGER NOT NULL, 
	resource_mode VARCHAR(10), 
	resource_count INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	created_by VARCHAR(36), 
	updated_by VARCHAR(36), 
	deleted_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_subtasks_type CHECK (type IN ('standard', 'resource', 'transactional')), 
	CONSTRAINT ck_subtasks_resource_mode CHECK (resource_mode IS NULL OR resource_mode IN ('count', 'details')), 
	CONSTRAINT ck_subtasks_resource_count_positive CHECK (resource_count IS NULL OR resource_count >= 1), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(task_id) REFERENCES tasks (id), 
	CONSTRAINT fk_subtasks_parent_subtask_id FOREIGN KEY(parent_subtask_id) REFERENCES subtasks (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(updated_by) REFERENCES users (id)
);
CREATE INDEX idx_subtasks_project_live ON subtasks (project_id, deleted_at);
CREATE INDEX idx_subtasks_task_live ON subtasks (task_id, deleted_at);
CREATE INDEX idx_subtasks_task_position ON subtasks (task_id, position);
CREATE INDEX ix_subtasks_deleted_at ON subtasks (deleted_at);
CREATE INDEX ix_subtasks_id ON subtasks (id);
CREATE INDEX ix_subtasks_name ON subtasks (name);
CREATE INDEX ix_subtasks_parent_subtask_id ON subtasks (parent_subtask_id);
CREATE INDEX ix_subtasks_project_id ON subtasks (project_id);
CREATE INDEX ix_subtasks_task_id ON subtasks (task_id);
CREATE UNIQUE INDEX uq_subtasks_subtask_position_live ON subtasks (parent_subtask_id, position) WHERE deleted_at IS NULL AND parent_subtask_id IS NOT NULL;
CREATE UNIQUE INDEX uq_subtasks_task_position_top_live ON subtasks (task_id, position) WHERE deleted_at IS NULL AND parent_subtask_id IS NULL;

-- ===== task_dependencies =====
CREATE TABLE task_dependencies (
	id VARCHAR(36) NOT NULL, 
	source_task_id VARCHAR(36) NOT NULL, 
	target_task_id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	created_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	FOREIGN KEY(source_task_id) REFERENCES tasks (id), 
	FOREIGN KEY(target_task_id) REFERENCES tasks (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_task_deps_project_live ON task_dependencies (project_id, deleted_at);
CREATE INDEX idx_task_deps_source_live ON task_dependencies (source_task_id, deleted_at);
CREATE INDEX idx_task_deps_target_live ON task_dependencies (target_task_id, deleted_at);
CREATE INDEX ix_task_dependencies_deleted_at ON task_dependencies (deleted_at);
CREATE INDEX ix_task_dependencies_id ON task_dependencies (id);
CREATE INDEX ix_task_dependencies_project_id ON task_dependencies (project_id);
CREATE INDEX ix_task_dependencies_source_task_id ON task_dependencies (source_task_id);
CREATE INDEX ix_task_dependencies_target_task_id ON task_dependencies (target_task_id);
CREATE UNIQUE INDEX uq_task_deps_pair_live ON task_dependencies (source_task_id, target_task_id) WHERE deleted_at IS NULL;

-- ===== task_resources =====
CREATE TABLE task_resources (
	id VARCHAR(36) NOT NULL, 
	task_id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	resource_name VARCHAR(255) NOT NULL, 
	onboard_date DATETIME, 
	actual_onboard_date DATETIME, 
	offboard_date DATETIME, 
	actual_offboard_date DATETIME, 
	position VARCHAR(255), 
	designation VARCHAR(255), 
	job_role VARCHAR(255), 
	qualification VARCHAR(255), 
	experience_years NUMERIC(4, 1), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(task_id) REFERENCES tasks (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id)
);
CREATE INDEX idx_task_resources_project_live ON task_resources (project_id, deleted_at);
CREATE INDEX ix_task_resources_deleted_at ON task_resources (deleted_at);
CREATE INDEX ix_task_resources_id ON task_resources (id);
CREATE INDEX ix_task_resources_project_id ON task_resources (project_id);
CREATE INDEX ix_task_resources_task_id ON task_resources (task_id);
CREATE UNIQUE INDEX uq_task_resources_task_live ON task_resources (task_id) WHERE deleted_at IS NULL;

-- ===== tasks =====
CREATE TABLE tasks (
	id VARCHAR(36) NOT NULL, 
	project_id VARCHAR(36) NOT NULL, 
	activity_id VARCHAR(36) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	type VARCHAR(20) NOT NULL, 
	start_date DATETIME NOT NULL, 
	end_date DATETIME NOT NULL, 
	actual_start_date DATETIME, 
	actual_end_date DATETIME, 
	position INTEGER NOT NULL, 
	resource_mode VARCHAR(10), 
	resource_count INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	created_by VARCHAR(36), 
	updated_by VARCHAR(36), 
	deleted_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_tasks_type CHECK (type IN ('standard', 'resource', 'transactional')), 
	CONSTRAINT ck_tasks_resource_mode CHECK (resource_mode IS NULL OR resource_mode IN ('count', 'details')), 
	CONSTRAINT ck_tasks_resource_count_positive CHECK (resource_count IS NULL OR resource_count >= 1), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(activity_id) REFERENCES activities (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(updated_by) REFERENCES users (id)
);
CREATE INDEX idx_tasks_activity_live ON tasks (activity_id, deleted_at);
CREATE INDEX idx_tasks_activity_position ON tasks (activity_id, position);
CREATE INDEX idx_tasks_project_live ON tasks (project_id, deleted_at);
CREATE INDEX ix_tasks_activity_id ON tasks (activity_id);
CREATE INDEX ix_tasks_deleted_at ON tasks (deleted_at);
CREATE INDEX ix_tasks_id ON tasks (id);
CREATE INDEX ix_tasks_name ON tasks (name);
CREATE INDEX ix_tasks_project_id ON tasks (project_id);
CREATE UNIQUE INDEX uq_tasks_activity_position_live ON tasks (activity_id, position) WHERE deleted_at IS NULL;

-- ===== user_permissions =====
CREATE TABLE user_permissions (
	user_id VARCHAR(36) NOT NULL, 
	permission_code VARCHAR(128) NOT NULL, 
	created_at DATETIME NOT NULL, 
	created_by VARCHAR(36), 
	PRIMARY KEY (user_id, permission_code), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(permission_code) REFERENCES permissions (code), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);
CREATE INDEX idx_user_permissions_permission ON user_permissions (permission_code);
CREATE INDEX idx_user_permissions_user ON user_permissions (user_id);

-- ===== user_roles =====
CREATE TABLE user_roles (
	user_id VARCHAR(36) NOT NULL, 
	role_id INTEGER NOT NULL, 
	created_at DATETIME NOT NULL, 
	created_by VARCHAR(36), 
	PRIMARY KEY (user_id, role_id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(role_id) REFERENCES roles (id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);
CREATE INDEX idx_user_roles_role ON user_roles (role_id);
CREATE INDEX idx_user_roles_user ON user_roles (user_id);

-- ===== users =====
CREATE TABLE users (
	id VARCHAR(36) NOT NULL, 
	user_code VARCHAR(50), 
	login VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	hashed_password VARCHAR(255) NOT NULL, 
	first_name VARCHAR(255), 
	last_name VARCHAR(255), 
	status VARCHAR(50) NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	refresh_token_jti VARCHAR(64), 
	refresh_token_expires_at DATETIME, 
	previous_refresh_token_jti VARCHAR(64), 
	previous_refresh_token_jti_valid_until DATETIME, 
	vendor_id VARCHAR(36), 
	division VARCHAR(32), 
	division_other VARCHAR(255), 
	phone_number VARCHAR(50), 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	CONSTRAINT fk_users_vendor_id FOREIGN KEY(vendor_id) REFERENCES vendors (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_users_created_at ON users (created_at);
CREATE INDEX idx_users_deleted_at ON users (deleted_at);
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_login ON users (login);
CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_vendor_id ON users (vendor_id);
CREATE INDEX ix_users_created_at ON users (created_at);
CREATE INDEX ix_users_deleted_at ON users (deleted_at);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE INDEX ix_users_id ON users (id);
CREATE UNIQUE INDEX ix_users_login ON users (login);
CREATE UNIQUE INDEX ix_users_user_code ON users (user_code);
CREATE INDEX ix_users_vendor_id ON users (vendor_id);

-- ===== vendors =====
CREATE TABLE vendors (
	id VARCHAR(36) NOT NULL, 
	vendor_code VARCHAR(50), 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	active BOOLEAN NOT NULL, 
	email VARCHAR(255), 
	contact_person VARCHAR(255), 
	phone_number VARCHAR(50), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	deleted_at DATETIME, 
	deleted_by VARCHAR(36), 
	PRIMARY KEY (id), 
	FOREIGN KEY(deleted_by) REFERENCES users (id)
);
CREATE INDEX idx_vendors_active_name ON vendors (active, name);
CREATE INDEX idx_vendors_created_at ON vendors (created_at);
CREATE INDEX idx_vendors_deleted_at ON vendors (deleted_at);
CREATE INDEX idx_vendors_email ON vendors (email);
CREATE INDEX ix_vendors_active ON vendors (active);
CREATE INDEX ix_vendors_created_at ON vendors (created_at);
CREATE INDEX ix_vendors_deleted_at ON vendors (deleted_at);
CREATE INDEX ix_vendors_email ON vendors (email);
CREATE INDEX ix_vendors_id ON vendors (id);
CREATE UNIQUE INDEX ix_vendors_name ON vendors (name);
CREATE UNIQUE INDEX ix_vendors_vendor_code ON vendors (vendor_code);

-- ===== work_package_types =====
CREATE TABLE work_package_types (
	id INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	internal_name VARCHAR(100) NOT NULL, 
	is_builtin BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	position INTEGER NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_work_package_types_internal_name UNIQUE (internal_name)
);
CREATE INDEX idx_work_package_types_position ON work_package_types (position);
CREATE INDEX ix_work_package_types_id ON work_package_types (id);
CREATE UNIQUE INDEX ix_work_package_types_internal_name ON work_package_types (internal_name);
CREATE INDEX ix_work_package_types_name ON work_package_types (name);
CREATE INDEX ix_work_package_types_position ON work_package_types (position);

-- ===== work_packages =====
CREATE TABLE work_packages (
	id INTEGER NOT NULL, 
	subject VARCHAR(255) NOT NULL, 
	description TEXT, 
	project_id VARCHAR(36) NOT NULL, 
	parent_id INTEGER, 
	type_id INTEGER, 
	assignee_id VARCHAR(36), 
	status VARCHAR(100) NOT NULL, 
	priority VARCHAR(100) NOT NULL, 
	done_ratio INTEGER NOT NULL, 
	start_date DATETIME, 
	end_date DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(parent_id) REFERENCES work_packages (id), 
	FOREIGN KEY(type_id) REFERENCES work_package_types (id), 
	FOREIGN KEY(assignee_id) REFERENCES users (id)
);
CREATE INDEX idx_work_packages_assignee_id ON work_packages (assignee_id);
CREATE INDEX idx_work_packages_parent_id ON work_packages (parent_id);
CREATE INDEX idx_work_packages_priority ON work_packages (priority);
CREATE INDEX idx_work_packages_project_id ON work_packages (project_id);
CREATE INDEX idx_work_packages_status ON work_packages (status);
CREATE INDEX idx_work_packages_subject ON work_packages (subject);
CREATE INDEX idx_work_packages_type_id ON work_packages (type_id);
CREATE INDEX ix_work_packages_assignee_id ON work_packages (assignee_id);
CREATE INDEX ix_work_packages_id ON work_packages (id);
CREATE INDEX ix_work_packages_parent_id ON work_packages (parent_id);
CREATE INDEX ix_work_packages_priority ON work_packages (priority);
CREATE INDEX ix_work_packages_project_id ON work_packages (project_id);
CREATE INDEX ix_work_packages_status ON work_packages (status);
CREATE INDEX ix_work_packages_subject ON work_packages (subject);
CREATE INDEX ix_work_packages_type_id ON work_packages (type_id);

-- FK-correct creation order (use this if running by hand):
--   divisions
--   permissions
--   project_status_transitions
--   resource_types
--   roles
--   users
--   work_package_types
--   comments
--   projects
--   revoked_tokens
--   role_permissions
--   user_permissions
--   user_roles
--   vendors
--   attachments
--   meetings
--   milestones
--   project_audit_logs
--   project_members
--   project_vendors
--   work_packages
--   activities
--   meeting_agenda_items
--   meeting_participants
--   milestone_dependencies
--   milestone_vendors
--   activity_dependencies
--   activity_resources
--   tasks
--   subtasks
--   task_dependencies
--   task_resources
--   subtask_dependencies
--   subtask_resources
