"""Generate a flat ``POSTMAN_CURLS.md`` of copy-paste curls from the
generated Postman collection.

Reads ``PMIS_API_Collection.postman_collection.json`` (sibling of
this repo root), walks the folder/item tree, emits one curl per
request into a markdown file grouped by folder. Variables
``{{baseUrl}}``, ``{{accessToken}}``, and path placeholders
(``:project_uuid`` etc.) are left as-is so they're trivial to
find-replace.

Run after ``scripts/generate_postman_collection.py`` so the curls
match the live OpenAPI surface. The two outputs sit side-by-side
at the repo root.

Usage:
    python scripts/generate_curls.py
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
COLLECTION = REPO_ROOT / "PMIS_API_Collection.postman_collection.json"
OUTPUT = REPO_ROOT / "POSTMAN_CURLS.md"


def _flatten_items(items: List[dict], parent_path: Tuple[str, ...] = ()) -> Iterable[Tuple[Tuple[str, ...], dict]]:
    for it in items:
        if "item" in it:
            yield from _flatten_items(it["item"], parent_path + (it["name"],))
        elif "request" in it:
            yield parent_path, it


def _curl_for(item: dict) -> str:
    req = item["request"]
    method = req.get("method", "GET").upper()
    url_raw = req.get("url", {}).get("raw", "")

    parts: List[str] = [f"curl -X {method} '{url_raw}'"]
    for h in req.get("header", []) or []:
        if h.get("disabled"):
            continue
        key = h.get("key", "")
        val = h.get("value", "")
        val_safe = val.replace("'", "'\\''")
        parts.append(f"  -H '{key}: {val_safe}'")

    body = req.get("body") or {}
    if body.get("mode") == "raw":
        raw = body.get("raw", "")
        if raw:
            body_safe = raw.replace("'", "'\\''")
            parts.append(f"  -d '{body_safe}'")

    return " \\\n".join(parts)


def main() -> None:
    if not COLLECTION.exists():
        raise SystemExit(
            f"{COLLECTION.name} not found in {REPO_ROOT}. "
            "Run scripts/generate_postman_collection.py first."
        )

    data = json.loads(COLLECTION.read_text(encoding="utf-8"))
    name = data.get("info", {}).get("name", "API")
    desc = data.get("info", {}).get("description", "")

    out: List[str] = []
    out.append(f"# {name} — direct curls\n")
    out.append(
        "> Auto-generated by `scripts/generate_curls.py` from "
        f"`{COLLECTION.name}`. Re-run after the Postman collection is "
        "regenerated so this file stays in sync.\n"
    )
    if desc:
        out.append(f"\n{desc}\n")
    out.append(
        "\n## How to use\n\n"
        "1. Replace `{{baseUrl}}` with the service URL — typically "
        "`http://10.1.131.199:8000` for the monolith or "
        "`http://10.1.131.199:8001` for user-mgmt.\n"
        "2. Replace `{{accessToken}}` with a bearer JWT from the "
        "user-mgmt login flow (Authenticate → Send OTP → Verify OTP). "
        "On the dev server the universal OTP is `000000`.\n"
        "3. Replace path placeholders like `:project_uuid`, "
        "`:vendor_id`, `:milestone_id` with real IDs.\n"
        "4. Replace empty body fields (`\"name\": \"\"` etc.) with "
        "your values before firing.\n\n"
        "On Windows PowerShell, swap single-quoted bodies for double-"
        "quoted with escaped inner quotes, or run from Git Bash / WSL "
        "where the quoting works as written.\n\n"
        "---\n"
    )

    by_folder: dict[str, List[dict]] = {}
    for parent, item in _flatten_items(data.get("item", [])):
        folder = " / ".join(parent) if parent else "(top-level)"
        by_folder.setdefault(folder, []).append(item)

    for folder in sorted(by_folder.keys()):
        out.append(f"\n## {folder}\n")
        for item in sorted(by_folder[folder], key=lambda it: it["name"]):
            req_name = item["name"]
            method = item["request"].get("method", "GET").upper()
            url_raw = item["request"].get("url", {}).get("raw", "")
            req_desc = item["request"].get("description", "").strip()

            out.append(f"\n### {method} — {req_name}\n")
            out.append(f"`{method} {url_raw}`\n")
            if req_desc:
                first_para = req_desc.split("\n\n", 1)[0]
                out.append(f"\n{first_para}\n")
            out.append("\n```bash\n")
            out.append(_curl_for(item))
            out.append("\n```\n")

    OUTPUT.write_text("".join(out), encoding="utf-8")
    n_requests = sum(len(v) for v in by_folder.values())
    print(f"Wrote {OUTPUT}")
    print(f"  {len(by_folder)} folders, {n_requests} requests")


if __name__ == "__main__":
    main()
