"""Dump DDL for every model on Base.metadata.

Two output files are produced under ``scripts/ddl/``:

- ``schema_postgres.sql`` — CREATE TABLE / CREATE INDEX statements rendered
  for the PostgreSQL dialect. This is the canonical schema file for prod;
  Alembic still owns migration management, but having a "from-scratch"
  DDL on disk is useful for reviews, ops, and disaster-recovery rebuilds.
- ``schema_sqlite.sql`` — Same DDL rendered for SQLite. Matches what
  ``Base.metadata.create_all`` produces in tests.

Both files are deterministic (alphabetical table order, no timestamps in
the output) so diffs from ``git status`` highlight only real schema changes
when you re-run the script after editing models.

Usage:
    .venv/Scripts/python.exe scripts/generate_ddl.py

Run this whenever a model changes. CI can also be wired to compare the
generated files against committed copies and fail on drift.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make ``app`` importable when this script is run directly from the repo
# root (``python scripts/generate_ddl.py``). When run via ``python -m`` the
# CWD is already on sys.path; this is a no-op in that case.
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql, sqlite
from sqlalchemy.schema import (
    CreateIndex, CreateSchema, CreateTable, MetaData, Table,
)

# Importing the package side-effects every model class onto Base.metadata.
from app.infrastructure.db import models  # noqa: F401, E402
from app.infrastructure.db.session import Base  # noqa: E402


OUT_DIR = REPO_ROOT / "scripts" / "ddl"


def _emit_ddl(metadata: MetaData, dialect) -> str:
    """Walk metadata in deterministic order and emit DDL strings."""
    lines: list[str] = []
    lines.append(f"-- Auto-generated by scripts/generate_ddl.py — DO NOT edit.")
    lines.append(f"-- Dialect: {dialect.name}")
    lines.append(f"-- Source: SQLAlchemy Base.metadata")
    lines.append("")

    # Sort tables alphabetically for deterministic output (FK ordering still
    # matters for execution; we add a trailing comment with the FK-resolved
    # creation order at the bottom of the file).
    tables = sorted(metadata.tables.values(), key=lambda t: t.name)

    for table in tables:
        lines.append(f"-- ===== {table.name} =====")
        ct = CreateTable(table).compile(dialect=dialect)
        lines.append(str(ct).strip().rstrip(";") + ";")
        # Indexes (skip the implicit indexes the dialect creates with the
        # table; only emit explicit ones from __table_args__).
        for ix in sorted(table.indexes, key=lambda i: i.name or ""):
            ddl = CreateIndex(ix).compile(dialect=dialect)
            lines.append(str(ddl).strip().rstrip(";") + ";")
        lines.append("")

    # FK-correct creation order, useful when running this file directly.
    fk_ordered = [t.name for t in metadata.sorted_tables]
    lines.append("-- FK-correct creation order (use this if running by hand):")
    lines.extend(f"--   {n}" for n in fk_ordered)
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    pg_ddl = _emit_ddl(Base.metadata, postgresql.dialect())
    sl_ddl = _emit_ddl(Base.metadata, sqlite.dialect())

    pg_path = OUT_DIR / "schema_postgres.sql"
    sl_path = OUT_DIR / "schema_sqlite.sql"
    pg_path.write_text(pg_ddl, encoding="utf-8")
    sl_path.write_text(sl_ddl, encoding="utf-8")
    print(f"Wrote {pg_path}  ({pg_path.stat().st_size} bytes)")
    print(f"Wrote {sl_path}  ({sl_path.stat().st_size} bytes)")
    print(f"Tables: {len(Base.metadata.tables)}")


if __name__ == "__main__":
    main()
