"""
Project creation service.
"""
from typing import List, Optional
from datetime import datetime

from sqlalchemy.orm import Session

from .....domain.projects.project import Project
from .....infrastructure.db.repositories.project_owner_repository import (
    ProjectOwnerRepository,
)
from .....infrastructure.db.repositories.project_repository import ProjectRepository
from .....infrastructure.db.repositories.project_status_transition_repository import (
    ProjectStatusTransitionRepository,
)
from .....infrastructure.db.repositories.user_repository import UserRepository
from .....infrastructure.db.repositories.vendor_repository import VendorRepository
from .....shared.datetime import ensure_aware_utc
from .....shared.service_result import ServiceResult
from .....shared.utils import normalize_string

from .audit import ACTION_CREATE, project_snapshot, record_audit
from .transitions import (
    CATEGORY_OTHERS,
    PROJECT_CATEGORY_CHOICES,
    PROJECT_STATUS_CHOICES,
    STATUS_NEW,
)


def _verify_user_exists(db: Session, username: str) -> bool:
    return UserRepository(db).get_by_login(username) is not None


def create_project(
    db: Session,
    *,
    actor_id: Optional[int],
    name: str,
    description: Optional[str] = None,
    active: bool = True,
    public: bool = False,
    status_explanation: Optional[str] = None,
    parent_id: Optional[str] = None,
    status: str = STATUS_NEW,
    owner: Optional[str] = None,
    category: Optional[str] = None,
    category_other: Optional[str] = None,
    category_other_reason: Optional[str] = None,
    vendor_ids: Optional[List[str]] = None,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
) -> ServiceResult[Project]:
    """Create a new (non-version) project.

    The public handle (uuid) and the display code (project_code) are both
    server-generated by the repository. Commits the transaction on success.
    """
    name = normalize_string(name)
    if not name or len(name) > 255:
        return ServiceResult.fail(
            error="Invalid name. Must be 1-255 characters.",
            error_type="validation_error",
        )

    if description and len(description) > 5000:
        return ServiceResult.fail(
            error="Description too long. Maximum 5000 characters.",
            error_type="validation_error",
        )

    if status_explanation and len(status_explanation) > 5000:
        return ServiceResult.fail(
            error="Status explanation too long. Maximum 5000 characters.",
            error_type="validation_error",
        )

    # Status validation against the project_status_transitions catalog. The
    # in-code PROJECT_STATUS_CHOICES set still exists as a backstop for the
    # case where the catalog hasn't been seeded (e.g. tests on a fresh
    # in-memory DB before init_db has run); the table is the primary truth
    # whenever it has rows.
    transition_repo = ProjectStatusTransitionRepository(db)
    catalog_statuses = transition_repo.known_to_statuses()
    valid_statuses = catalog_statuses if catalog_statuses else list(PROJECT_STATUS_CHOICES)
    if status not in valid_statuses:
        return ServiceResult.fail(
            error=f"Invalid status '{status}'. Allowed: {', '.join(valid_statuses)}",
            error_type="invalid_status",
        )

    if category is not None and category not in PROJECT_CATEGORY_CHOICES:
        return ServiceResult.fail(
            error=f"Invalid category '{category}'.",
            error_type="validation_error",
        )

    # "others" category: categoryOther is required, non-empty, <= 255 chars.
    # For non-'others' categories the field must be None (accidentally setting
    # it is a client bug we reject with 422 rather than silently storing).
    if category == CATEGORY_OTHERS:
        co = normalize_string(category_other) if category_other else ""
        if not co:
            return ServiceResult.fail(
                error="categoryOther is required when category is 'others'.",
                error_type="validation_error",
            )
        if len(co) > 255:
            return ServiceResult.fail(
                error="categoryOther must be 1-255 characters.",
                error_type="validation_error",
            )
        category_other = co
        # categoryOtherReason: required when category='others', max 1000.
        cor = normalize_string(category_other_reason) if category_other_reason else ""
        if not cor:
            return ServiceResult.fail(
                error="categoryOtherReason is required when category is 'others'.",
                error_type="validation_error",
            )
        if len(cor) > 1000:
            return ServiceResult.fail(
                error="categoryOtherReason must be 1-1000 characters.",
                error_type="validation_error",
            )
        category_other_reason = cor
    else:
        if category_other is not None and normalize_string(category_other) != "":
            return ServiceResult.fail(
                error="categoryOther may only be provided when category is 'others'.",
                error_type="validation_error",
            )
        category_other = None
        if category_other_reason is not None and normalize_string(category_other_reason) != "":
            return ServiceResult.fail(
                error="categoryOtherReason may only be provided when category is 'others'.",
                error_type="validation_error",
            )
        category_other_reason = None

    # "Must be in the future" is enforced by the Pydantic schema; skip the
    # duplicate check here to avoid naive/aware datetime comparison bugs.
    start_utc = ensure_aware_utc(start_date)
    end_utc = ensure_aware_utc(end_date)
    if start_utc is not None and end_utc is not None and end_utc <= start_utc:
        return ServiceResult.fail(
            error="end_date must be after start_date",
            error_type="validation_error",
        )

    if owner is not None:
        if not _verify_user_exists(db, owner):
            return ServiceResult.fail(
                error=f"Owner user '{owner}' does not exist",
                error_type="validation_error",
            )
        # Validate against the project_owners master. Only users in the
        # whitelist can be set as a project owner. Skipped silently if the
        # catalog has no active rows (treated as "owner gating disabled" —
        # the init_db seed adds at least the bootstrap admin, so an empty
        # catalog only happens before init_db has run, e.g. fresh tests
        # using a per-test in-memory DB).
        from .....infrastructure.db.models.project_owner import ProjectOwnerModel
        catalog_populated = (
            db.query(ProjectOwnerModel.id)
            .filter(ProjectOwnerModel.active.is_(True))
            .first()
            is not None
        )
        if catalog_populated:
            owner_repo = ProjectOwnerRepository(db)
            if not owner_repo.is_login_an_active_owner(owner):
                return ServiceResult.fail(
                    error=(
                        f"User '{owner}' is not in the project_owners whitelist. "
                        f"Add them via POST /api/v3/project_owners/create first."
                    ),
                    error_type="validation_error",
                )

    repo = ProjectRepository(db)
    vendor_repo = VendorRepository(db)

    if parent_id is not None and not repo.exists_by_id(parent_id):
        return ServiceResult.fail(
            error=f"Parent project with ID {parent_id} does not exist",
            error_type="not_found",
        )

    # De-duplicate + validate vendor IDs.
    if vendor_ids:
        unique_vids = list(dict.fromkeys(vendor_ids))  # preserve order, unique
        ok_ids = set(vendor_repo.existing_active_ids(unique_vids))
        missing = [v for v in unique_vids if v not in ok_ids]
        if missing:
            return ServiceResult.fail(
                error=f"Unknown or inactive vendor(s): {', '.join(missing)}",
                error_type="validation_error",
            )
        vendor_ids = unique_vids
    else:
        vendor_ids = []

    try:
        project = repo.create(
            name=name,
            description=description,
            active=active,
            public=public,
            status_explanation=status_explanation,
            parent_id=parent_id,
            status=status,
            owner=owner,
            category=category,
            category_other=category_other,
            category_other_reason=category_other_reason,
            start_date=start_date,
            end_date=end_date,
            is_version=False,
            created_by=actor_id,
        )

        # Attach vendors (repository flushes but does not commit).
        if vendor_ids:
            vendor_repo.set_project_vendors(project.id, vendor_ids)
            # Refresh the domain object's vendor list for the response.
            project.vendors = vendor_repo.list_project_vendors(project.id)

        record_audit(
            db,
            project_id=project.id,
            actor_id=actor_id,
            action=ACTION_CREATE,
            before=None,
            after=project_snapshot(project),
        )

        db.commit()
        return ServiceResult.ok(project)

    except Exception as e:
        db.rollback()
        return ServiceResult.fail(
            error=f"Failed to create project: {str(e)}",
            error_type="internal_error",
        )
