"""
Project creation service.
"""
from typing import List, Optional
from datetime import datetime

from sqlalchemy.orm import Session

from .....domain.projects.project import Project
from .....infrastructure.db.repositories.project_repository import ProjectRepository
from .....infrastructure.db.repositories.user_repository import UserRepository
from .....infrastructure.db.repositories.vendor_repository import VendorRepository
from .....shared.datetime import ensure_aware_utc
from .....shared.service_result import ServiceResult
from .....shared.utils import normalize_string

from .audit import ACTION_CREATE, project_snapshot, record_audit
from .transitions import (
    CATEGORY_OTHERS,
    PROJECT_CATEGORY_CHOICES,
    PROJECT_STATUS_CHOICES,
    STATUS_NEW,
)


def _verify_user_exists(db: Session, username: str) -> bool:
    return UserRepository(db).get_by_login(username) is not None


def create_project(
    db: Session,
    *,
    actor_id: Optional[int],
    name: str,
    description: Optional[str] = None,
    active: bool = True,
    public: bool = False,
    status_explanation: Optional[str] = None,
    parent_id: Optional[str] = None,
    status: str = STATUS_NEW,
    owner: Optional[str] = None,
    category: Optional[str] = None,
    category_other: Optional[str] = None,
    vendor_ids: Optional[List[str]] = None,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
) -> ServiceResult[Project]:
    """Create a new (non-version) project.

    The public handle (uuid) and the display code (project_code) are both
    server-generated by the repository. Commits the transaction on success.
    """
    name = normalize_string(name)
    if not name or len(name) > 255:
        return ServiceResult.fail(
            error="Invalid name. Must be 1-255 characters.",
            error_type="validation_error",
        )

    if description and len(description) > 5000:
        return ServiceResult.fail(
            error="Description too long. Maximum 5000 characters.",
            error_type="validation_error",
        )

    if status_explanation and len(status_explanation) > 5000:
        return ServiceResult.fail(
            error="Status explanation too long. Maximum 5000 characters.",
            error_type="validation_error",
        )

    if status not in PROJECT_STATUS_CHOICES:
        return ServiceResult.fail(
            error=f"Invalid status '{status}'.",
            error_type="validation_error",
        )

    if category is not None and category not in PROJECT_CATEGORY_CHOICES:
        return ServiceResult.fail(
            error=f"Invalid category '{category}'.",
            error_type="validation_error",
        )

    # "others" category: categoryOther is required, non-empty, <= 255 chars.
    # For non-'others' categories the field must be None (accidentally setting
    # it is a client bug we reject with 422 rather than silently storing).
    if category == CATEGORY_OTHERS:
        co = normalize_string(category_other) if category_other else ""
        if not co:
            return ServiceResult.fail(
                error="categoryOther is required when category is 'others'.",
                error_type="validation_error",
            )
        if len(co) > 255:
            return ServiceResult.fail(
                error="categoryOther must be 1-255 characters.",
                error_type="validation_error",
            )
        category_other = co
    else:
        if category_other is not None and normalize_string(category_other) != "":
            return ServiceResult.fail(
                error="categoryOther may only be provided when category is 'others'.",
                error_type="validation_error",
            )
        category_other = None

    # "Must be in the future" is enforced by the Pydantic schema; skip the
    # duplicate check here to avoid naive/aware datetime comparison bugs.
    start_utc = ensure_aware_utc(start_date)
    end_utc = ensure_aware_utc(end_date)
    if start_utc is not None and end_utc is not None and end_utc <= start_utc:
        return ServiceResult.fail(
            error="end_date must be after start_date",
            error_type="validation_error",
        )

    if owner is not None and not _verify_user_exists(db, owner):
        return ServiceResult.fail(
            error=f"Owner user '{owner}' does not exist",
            error_type="validation_error",
        )

    repo = ProjectRepository(db)
    vendor_repo = VendorRepository(db)

    if parent_id is not None and not repo.exists_by_id(parent_id):
        return ServiceResult.fail(
            error=f"Parent project with ID {parent_id} does not exist",
            error_type="not_found",
        )

    # De-duplicate + validate vendor IDs.
    if vendor_ids:
        unique_vids = list(dict.fromkeys(vendor_ids))  # preserve order, unique
        ok_ids = set(vendor_repo.existing_active_ids(unique_vids))
        missing = [v for v in unique_vids if v not in ok_ids]
        if missing:
            return ServiceResult.fail(
                error=f"Unknown or inactive vendor(s): {', '.join(missing)}",
                error_type="validation_error",
            )
        vendor_ids = unique_vids
    else:
        vendor_ids = []

    try:
        project = repo.create(
            name=name,
            description=description,
            active=active,
            public=public,
            status_explanation=status_explanation,
            parent_id=parent_id,
            status=status,
            owner=owner,
            category=category,
            category_other=category_other,
            start_date=start_date,
            end_date=end_date,
            is_version=False,
            created_by=actor_id,
        )

        # Attach vendors (repository flushes but does not commit).
        if vendor_ids:
            vendor_repo.set_project_vendors(project.id, vendor_ids)
            # Refresh the domain object's vendor list for the response.
            project.vendors = vendor_repo.list_project_vendors(project.id)

        record_audit(
            db,
            project_id=project.id,
            actor_id=actor_id,
            action=ACTION_CREATE,
            before=None,
            after=project_snapshot(project),
        )

        db.commit()
        return ServiceResult.ok(project)

    except Exception as e:
        db.rollback()
        return ServiceResult.fail(
            error=f"Failed to create project: {str(e)}",
            error_type="internal_error",
        )
